name: Terraform CI/CD

on:
  push:
    branches:
      - code # Or your desired branch
  pull_request:
    branches:
      - code

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1 # Or your desired region

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.1 # Specify your desired Terraform version Terraform v1.11.1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true # Allow subsequent steps even if formatting is off

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan (on Pull Request)
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        env:
          TF_VAR_environment: development # Example variable for a dev environment

      - name: Terraform Apply (on Push to Main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        env:
          TF_VAR_environment: production # Example variable for a prod environment
